<?php

/**
 * @file
 * hook into the menu.
 */

function datasetentry_menu() {
	$items['datasetentry'] = array(
		'title' => 'Data Set Entry',
		'page callback' => 'datasetentry_index',
		//'access arguments' => array('access content'),
		'access callback' => 'user_is_logged_in'
	);

	return $items;
}

function datasetentry_theme() {
	return array(
		'datasetentry'=> array(
			'template' => 'theIndexPage',
		),
	);
}

function datasetentry_index() {

	drupal_add_library('angularjs','angularjs');
	//drupal_add_library('system','ui.datepicker');

  	$path = drupal_get_path('module','datasetentry');  //Get the Drupal Path to our module

    global $user;
    drupal_add_js(array('datasetentry' => array('path' => $path,
    									  'user_name' => $user->name,
    									  'userid' => $user->uid)), 'setting');

    //drupal_add_js(array('datasetentry' => array('user_name' => $user->name)), 'setting');
    //drupal_add_js(array('datasetentry' => array('userid' => $user->uid)), 'setting');

	//drupal_add_js('https://ajax.googleapis.com/ajax/libs/angularjs/1.3.4/angular-animate.min.js');
	//drupal_add_js('https://ajax.googleapis.com/ajax/libs/angularjs/1.3.4/angular-aria.min.js');
	drupal_add_js($path.'/angularscripts/app.js');
	drupal_add_js('https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.3.0/Chart.js', 'external');
	drupal_add_js('https://cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.11.0/bootstrap-table.min.js', 'external');
	drupal_add_css('https://ajax.googleapis.com/ajax/libs/angular_material/1.0.9/angular-material.min.css', 'external');
	drupal_add_css('https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css', 'external');
	drupal_add_css('https://cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.11.0/bootstrap-table.min.css', 'external');
	drupal_add_js('https://ajax.googleapis.com/ajax/libs/angular_material/1.0.9/angular-material.js', 'external');
	drupal_add_css($path.'/css/css.css');
	drupal_add_js($path.'/externalscripts/angular-chart.min.js');
	drupal_add_js($path.'/externalscripts/dirPagination.js');
	drupal_add_js($path.'/externalscripts/ui-bootstrap-tpls-2.1.4.min.js');
	drupal_add_js($path.'/externalscripts/ng-file-upload-shim.min.js');
	drupal_add_js($path.'/externalscripts/ng-file-upload.min.js');

	return theme('datasetentry');
}
